# Generated by Django 5.0 on 2023-12-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_breeds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breeds',
            new_name='Breed',
        ),
    ]
