# Generated by Django 5.0 on 2023-12-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_rename_breeds_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='type',
        ),
        migrations.AddField(
            model_name='breed',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Deceased', 'Deceased')], max_length=200, null=True),
        ),
    ]
