# Generated by Django 5.0 on 2023-12-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_remove_breed_type_breed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='name',
        ),
        migrations.AddField(
            model_name='breed',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoapp.user'),
        ),
    ]
