# Generated by Django 5.0 on 2023-12-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_remove_breed_name_breed_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Deceased', 'Deceased')], max_length=200, null=True)),
                ('where', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='breed',
            name='status',
        ),
        migrations.AddField(
            model_name='breed',
            name='tags',
            field=models.ManyToManyField(to='djangoapp.tag'),
        ),
    ]
