# Generated by Django 5.0 on 2023-12-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_misc_tag_remove_breed_status_breed_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='price',
            new_name='age',
        ),
    ]
