# Generated by Django 5.0 on 2023-12-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_breed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='breedname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
