# Generated by Django 5.0 on 2023-12-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_breed_breedname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Misc',
        ),
        migrations.AddField(
            model_name='breed',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Deceased', 'Deceased')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='where',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=200, null=True),
        ),
    ]
