# Generated by Django 5.0 on 2023-12-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_remove_breed_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='where',
        ),
    ]
