# Generated by Django 5.0 on 2023-12-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_remove_breed_where'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usersinfo',
        ),
    ]
